### ISSUE TITLE
[FEATURE]: Control the type of the Loadbalancer being created for clusterlink.

### ISSUE THREAD

**Issue by aviweit** [clusterlink-net/clusterlink#529]
We have a scenario where we want clusterlink peers to communicate privately using cloud VPEs.

In-order to achieve that, we need to create an EndpointService around clusterlink.
For that, cloud vendors require the loadbalancer to be from a specific type.

Currently, the loadbalancer being created by `clusterlink deploy peer` does not meet cloud vendor requirements.

AWS requires the LB to be from type network and GCP -- internal.

This can be achieved by setting proper annotations in the Service CR:

AWS: service.beta.kubernetes.io/aws-load-balancer-type: nlb
GCP: networking.gke.io/load-balancer-type: "Internal"

Please refer to Service CR examples below:

**AWS**

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: clusterlink
  namespace: clusterlink-system
spec:
  type: LoadBalancer
  selector:
    app: cl-dataplane
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
 ```
 
**GCP**

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  name: clusterlink
  namespace: clusterlink-system
spec:
  type: LoadBalancer
  selector:
    app: cl-dataplane
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
```

Thanks.
